--- 
repos:

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json

-   repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks: 
    -   id: black
        language_version: python3

-   repo: local
    hooks:
    -   id: python-tests
        name: pytests
        entry: pytest src/tests
        language: python
        additional_dependencies: [pre-commit, pytest, pandas]
        always_run: true
        pass_filenames: false